### ISSUE TITLE
Incompatability with Handynotes: Dragonflight

### ISSUE THREAD

**Issue by Beet4** [herumph/MythicPlusLoot#35]
Issue https://github.com/herumph/MythicPlusLoot/issues/31 is still existing. However not when only your addon is enabled. I narrowed it down to Handynotes: Dragonflight in my case which also uses LibUIDropDownMenu but a newer version.

The version you are using: -- $Id: LibUIDropDownMenu.lua 57 2020-10-20 13:44:40Z arithmandar $
Handynotes: Dragonflight: -- $Id: LibUIDropDownMenu.lua 117 2022-11-29 15:36:42Z arithmandar $

I am no coder by any means but does it perhaps have something to do with what is mentioned in https://github.com/herumph/MythicPlusLoot/issues/29 in regards to generically named public functions in your addon, then your addon maybe pulls functions from wrong lib of another addon due to this?

**Comment by Beet4** [comment]
As said in https://github.com/herumph/MythicPlusLoot/issues/31, manually replacing the lib in MythicPlusLoot folder with LibUIDropDownMenu-v4.17.10000046801 is a work around for now.

**Comment by herumph** [comment]
@Beet4 I've downloaded Handynotes and am unable to reproduce any errors. I've gone ahead and updated the LibUI Menus in the addon to hopefully have it working now. A new update is out now. Please let me know if this solves the issue. 

Given that updating LibUI fixes the issue for you, I don't see this as an issue related to functions in the code. However, I could be wrong.

**Comment by Beet4** [comment]
@herumph Seems to be resolved with the new lib, I no longer get any LUA errors on login.

Did you ever try with the Dragonflight plugin for handynotes? https://www.curseforge.com/wow/addons/handynotes-dragonflight

I did not get the conflict with only base Handynotes enabled, only with the Dragonflight plugin for the base addon.

I guess you can close this now. :)

**Comment by herumph** [comment]
I tried both Handynotes and Handynotes: Dragonflight. Weird that I wasn't getting the same error but at least it's solved now.
