### ISSUE TITLE
Gear from older dungeons does not scale properly

### ISSUE THREAD

**Issue by Beet4** [herumph/MythicPlusLoot#36]
Gear from dungeons from previous expansions does not scale correctly on M+17 upwards and in Great Vault sections.

M+16:
![image](https://user-images.githubusercontent.com/38279393/207161370-ab16110b-4c50-4fec-b4a4-adfc18fbb4bf.png)

M+17:
![image](https://user-images.githubusercontent.com/38279393/207161392-8742f2de-3693-4157-a73c-343e915d1c38.png)

All great vault sections:
![image](https://user-images.githubusercontent.com/38279393/207161464-79896708-4a1f-46dc-82af-e36a4b280ea6.png)

**Comment by herumph** [comment]
This is a known issue and is a problem with Blizzard's item scaling of previous expansions items. This cannot be fixed currently
