### ISSUE TITLE
wago.io does not seem updated

### ISSUE THREAD

**Issue by JVemmer** [herumph/MythicPlusLoot#40]
The version of MythicPlusLoot hosted on [wago.io](https://addons.wago.io/addons/mythicplusloot) appears to be a version behind the one on [curseforge](https://www.curseforge.com/wow/addons/mythic-plus-loot). It therefore does not currently display the proper Dragonflight dungeons.

**Comment by herumph** [comment]
You are correct. It slipped my mind to update the wago.io version. That version is now updated.
