### ISSUE TITLE
Shadowmoon Burial Grounds contains loot from non-Mythic+ tables

### ISSUE THREAD

**Issue by RamyRafik** [herumph/MythicPlusLoot#41]
Loot table for Shadomoon Burial Grounds contain items from non-Mythic-Plus loot tables, which is a HUGE list.

Example, as a hunter, I can see 8 possible necklaces, They are actually coming from the Normal/Heroic/Mythic loot tables.
![Wrong](https://user-images.githubusercontent.com/20221435/208626891-37f0d39d-d875-45f8-8854-73cdf5194bc9.png)

While in-fact, Mythic Plus has no possible necklaces.
![Correct](https://user-images.githubusercontent.com/20221435/208627027-dcbd4459-e85c-4db6-a3c7-c643d5cd2689.png)

**Comment by herumph** [comment]
Items used to be manually input but with updates to class/spec filtering that was not feasible. Now items are gathered from wowhead but clearly that’s not a good solution. 

I’ll work on using the API to get items hopefully in game so they are more accurate. Thanks for the report.

**Comment by herumph** [comment]
Items are now sourced through the adventure guide so this should no longer be an issue. Thanks again for the issue report.
