### ISSUE TITLE
Dungeon and Item Ids?

### ISSUE THREAD

**Issue by thelewisking** [herumph/MythicPlusLoot#52]
As we move into 10.2 - Where are the dungeon and item IDs stored? Looking and the code it seems straightfoward to update but I daresay it'd be hard to just guess the values...

**Comment by TwoBootsMcGee** [comment]
> As we move into 10.2 - Where are the dungeon and item IDs stored? Looking and the code it seems straightfoward to update but I daresay it'd be hard to just guess the values...

I noticed you added a PR updated for Season 3. Did you end up finding those dungeon ID's somewhere? Thanks!

**Comment by thelewisking** [comment]
Hey, I've added links to the DB location in the updated readme.

The DB is named JournalInstance and wago (the weakaura guys) fortunately scrape it very accessibly!

https://wago.tools/db2/JournalInstance

It's not the dungeon ID itself we wanted but it's respective dungeon journal Id.

Happy hunting
